// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Blaze1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void blaze1() {
    driver.Navigate().GoToUrl("https://blazedemo.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1075, 824);
    driver.FindElement(By.Name("fromPort")).Click();
    {
      var dropdown = driver.FindElement(By.Name("fromPort"));
      dropdown.FindElement(By.XPath("//option[. = 'Boston']")).Click();
    }
    driver.FindElement(By.Name("toPort")).Click();
    {
      var dropdown = driver.FindElement(By.Name("toPort"));
      dropdown.FindElement(By.XPath("//option[. = 'Rome']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .btn")).Click();
    driver.FindElement(By.Id("inputName")).Click();
    driver.FindElement(By.Id("inputName")).SendKeys("Bob Jomes");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("inputName")).Click();
    driver.FindElement(By.Id("inputName")).Click();
    driver.FindElement(By.Id("inputName")).SendKeys("Bob Jones");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("456 Main St");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Atown");
    driver.FindElement(By.Id("state")).Click();
    driver.FindElement(By.Id("state")).SendKeys("NA");
    driver.FindElement(By.Id("zipCode")).Click();
    driver.FindElement(By.Id("zipCode")).SendKeys("23456");
    driver.FindElement(By.Id("creditCardNumber")).Click();
    driver.FindElement(By.Id("creditCardNumber")).SendKeys("1111222233334444");
    driver.FindElement(By.Id("creditCardMonth")).Click();
    driver.FindElement(By.Id("creditCardMonth")).SendKeys("1");
    driver.FindElement(By.Id("creditCardYear")).Click();
    driver.FindElement(By.Id("creditCardYear")).SendKeys("2016");
    driver.FindElement(By.CssSelector(".control-group:nth-child(11)")).Click();
    driver.FindElement(By.Id("nameOnCard")).Click();
    driver.FindElement(By.Id("nameOnCard")).SendKeys("Bob Jones");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.LinkText("Travel The World")).Click();
    driver.FindElement(By.Name("fromPort")).Click();
    {
      var dropdown = driver.FindElement(By.Name("fromPort"));
      dropdown.FindElement(By.XPath("//option[. = 'Philadelphia']")).Click();
    }
    driver.FindElement(By.Name("toPort")).Click();
    {
      var dropdown = driver.FindElement(By.Name("toPort"));
      dropdown.FindElement(By.XPath("//option[. = 'London']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(5) .btn")).Click();
    driver.FindElement(By.Id("inputName")).Click();
    driver.FindElement(By.Id("inputName")).SendKeys("Alice");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("101 George St");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Newtown");
    driver.FindElement(By.CssSelector(".control-group:nth-child(5)")).Click();
    driver.FindElement(By.Id("state")).Click();
    driver.FindElement(By.Id("state")).SendKeys("NA");
    driver.FindElement(By.Id("zipCode")).Click();
    driver.FindElement(By.Id("zipCode")).SendKeys("20000");
    driver.FindElement(By.CssSelector(".control-group:nth-child(7) > .controls")).Click();
    driver.FindElement(By.Id("cardType")).Click();
    {
      var dropdown = driver.FindElement(By.Id("cardType"));
      dropdown.FindElement(By.XPath("//option[. = 'American Express']")).Click();
    }
    driver.FindElement(By.Id("creditCardNumber")).Click();
    driver.FindElement(By.Id("creditCardNumber")).SendKeys("2222222222222222");
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.Id("creditCardMonth")).SendKeys("2");
    driver.FindElement(By.Id("creditCardYear")).Click();
    driver.FindElement(By.Id("creditCardYear")).SendKeys("2021");
    driver.FindElement(By.Id("nameOnCard")).Click();
    driver.FindElement(By.Id("nameOnCard")).SendKeys("Alice");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.LinkText("home")).Click();
    driver.FindElement(By.LinkText("BlazeDemo")).Click();
    driver.FindElement(By.LinkText("destination of the week! The Beach!")).Click();
    driver.FindElement(By.LinkText("Travel The World")).Click();
  }
}
