// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NGINX1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }
  [Test]
  public void nGINX1() {
    driver.Navigate().GoToUrl("https://blazedemo.com//en/");
    driver.Manage().Window.Size = new System.Drawing.Size(1073, 824);
    driver.FindElement(By.LinkText("Basic HTTP server features")).Click();
    driver.FindElement(By.LinkText("index")).Click();
    driver.FindElement(By.LinkText("Example Configuration")).Click();
    driver.FindElement(By.LinkText("Example Configuration")).Click();
    driver.FindElement(By.LinkText("index")).Click();
    driver.FindElement(By.LinkText("news")).Click();
    driver.FindElement(By.LinkText("русский")).Click();
    driver.FindElement(By.CssSelector("#menu > div")).Click();
    driver.FindElement(By.LinkText("english")).Click();
    driver.FindElement(By.LinkText("documentation")).Click();
    driver.FindElement(By.LinkText("Installing nginx")).Click();
    driver.FindElement(By.LinkText("documentation")).Click();
    driver.FindElement(By.LinkText("Building nginx from Sources")).Click();
    driver.FindElement(By.LinkText("documentation")).Click();
    driver.FindElement(By.LinkText("Beginner’s Guide")).Click();
    driver.FindElement(By.LinkText("documentation")).Click();
    driver.FindElement(By.LinkText("Admin’s Guide")).Click();
    {
      var element = driver.FindElement(By.LinkText("Installing NGINX and NGINX Plus"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.LinkText("Load Balancer")).Click();
    driver.FindElement(By.LinkText("HTTP Load Balancing")).Click();
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.LinkText("About F5 NGINX")).Click();
    vars["win5808"] = waitForWindow(2000);
    vars["root"] = driver.CurrentWindowHandle;
    driver.SwitchTo().Window(vars["win5808"].ToString());
    driver.Close();
    driver.SwitchTo().Window(vars["root"].ToString());
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".container-fluid:nth-child(3) > #nginx-products .col-xs-12:nth-child(5) .card-title")).Click();
    driver.FindElement(By.LinkText("Configuration")).Click();
    driver.FindElement(By.LinkText("Global Configuration")).Click();
    driver.FindElement(By.LinkText("ConfigMap Resource")).Click();
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.LinkText("worker_cpu_affinity")).Click();
    vars["win1569"] = waitForWindow(2000);
    driver.SwitchTo().Window(vars["win1569"].ToString());
    driver.Close();
    driver.SwitchTo().Window(vars["root"].ToString());
    driver.FindElement(By.LinkText("NGINX Ingress Controller")).Click();
    driver.FindElement(By.LinkText("Troubleshooting")).Click();
    driver.FindElement(By.LinkText("Troubleshooting VirtualServer Resources")).Click();
    driver.FindElement(By.CssSelector(".breadcrumb > li:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("NGINX Ingress Controller")).Click();
    driver.FindElement(By.CssSelector(".col-md-5:nth-child(5) > .card-body")).Click();
    driver.FindElement(By.LinkText("Logging And Monitoring")).Click();
    driver.FindElement(By.LinkText("Prometheus")).Click();
    driver.FindElement(By.LinkText("Status Page")).Click();
    driver.FindElement(By.LinkText("Logging")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
  }
}
